/* ZilogWarnings.h
 *   This file gives symbolic names to the warning numbers generated by
 *   Zilog compilers, for possible use in the warning pragma.
 *
 *   Syntax for the warning pragma is
 *
 *       #pragma warning <option><list> 
 *         where <option> is one of
 *            disable:  Disable generation of the warning
 *            enable:   Enable generation of the warning
 *            error:    Treat the warning as an error
 *            once:     Generate the warning once, then Disable
 *            suppress: Disable warning for next line only
 *         and <list> is a comma separated list of warning numbers
 *
 *       #pragma warning push  // save the current state of all warnings
 *       #pragma warning pop   // restore the state from a previous push
 *
 *   If it is intended to disable a warning thoughout a project (or to convert
 *   it to an error), Zilog recommends placing warning pragmas in an
 *   include file used by all the source files in the project. Use the push/pop
 *   and suppress options to disable (or convert) a warning in relatively small
 *   sections of code.
 *
 *   Note that some warning codes may be either a warning or an error depending
 *   on context.  Disabling a warning code will have no effect in contexts where
 *   the code would be an error.
 *
 *   Note on warnings generated in the Optimizer, Backend, and Assembler:
 *      Since the latter phases of the compiler tend to move code around,
 *      it is recommended that options targeted at these phases be established
 *      prior to the start of any function they are intended for and canceled,
 *      if at all, outside of that function.
 *
 *      Warnings generated by the latter phases of the compiler cannot be
 *      supressed.
 *
 *
 *  Copyright (C) 2012 by Ixys, Inc.
 *  All Rights Reserved.
 */

#pragma once // Include this file only once

/*
 * Warnings generated by the compiler preprocessor
 */
#define BAD_EOF               1 /* Concatination at end of file               */
#define BAD_REDEF             3 /* Illegal redefination of macro              */
#define BAD_ESCAPE_CHAR      18 /* Escape sequence ASCII code too large to fit
                                 * in char                                    */
#define BAD_CHAR_CONST       20 /* More than four characters in string
                                 * constant, e.g. 'abcde'                     */
#define BAD_POUND_POUND      23 /* "##" cannot be first or last token in
                                 * replacement                                */
#define BAD_POUND            24 /* "#" must be followed by an argument name   */
#define BAD_UNDEF            26 /* Cannot undefine macro                      */
#define DIV_ZERO             32 /* Division by zero encountered               */
#define BAD_PRAGMA           37 /* Unsupported or poorly formed pragma        */
#define EMPTY_FILE           44 /* Empty file encountered                     */
#define UNBALANCED_POP       45 /* Unbalanced pop of warning state            */
#define CANT_SUPPRESS        46 /* Only compiler frontend warnings can be
                                 * suppressed                                 */

/*
 * Warnings generated by the compiler front end
 */
#define ARG_MISMATCH        105 /* Argument type mismatch                     */
#define INT_TO_LARGE        111 /* Integer constant too large                 */
#define BAD_RET_TYPE        112 /* Expression not compatible with function
                                 * return type                                */
#define MUST_BE_TYPE_QUAL   124 /* Only type qualifiers may be specified
                                 * within pointer declarations                */
#define CANT_COMPARE_PTR    145 /* Pointers to different types may not be
                                 * compared                                   */
#define CANT_SUBTRACT_PTR   148 /* Pointers to different types may not be
                                 * subtracted                                 */
#define NPTR_TO_PTR         163 /* Casting a non-pointer to a pointer         */
#define ARG_TYPE_NOT_COMPAT 171 /* Argument type is not compatible with formal
                                 * parameter                                  */
#define NOT_CONSTANT        182 /* Static objects may be initialized with
                                 * constant expressions only                  */
#define BAD_INITIALIZER     195 /* Initializer is not assignment compatible   */
#define NO_PROTOTYPE        197 /* No function prototype [for function] in
                                 * scope                                      */
#define OLD_FUNCT_DECL      198 /* "old style" formal parameter declarations
                                 * are obsolete                               */

#define ONLY_ONE_SPACE      201 /* Only one memory space can be specified     */
#define BAD_TYPE_SPEC       202 /* Unrecognized/invalid type specifier        */
#define NO_PROMOTION        203 /* Integer promotion not performed            */
#define PARM_SPACE_IGNORED  204 /* Ignoring space specifier on local, parm, or
                                 * struct member                              */
#define CONST_OR_VIOLTLE_IGNRD 205 /* Ignoring const of violatile qualifier   */
#define FUNCT_SPACE_IGNORED 209 /* Ignoring space specifier on function       */
#define SPACE_IGNORED       204 /* Ignoring space specifier on local, parm, or
                                 * struct member                              */
#define RETURNS_INT         214 /* Function return type defaults to int       */
#define BAD_CAST            208 /*  Operands are not cast compatible          */
#define BAD_AUTO            218 /* Function definition declared auto          */
#define MUST_RETURN_VALUE   213 /* Function must return a value               */
#define SIGNED_UNSIGNED_MISMATCH 215 /* Signed/unsigned mismatch              */
#define FUNCTION_DEC_AUTO   218 /* Function definition declared auto          */
#define NO_ARITH_ON_FPTR    220 /* Cannot perform pointer arithmetic on function
                                 * pointer                                    */
#define TYPE_DFLTS_TO_INT   221 /* Type defaults to int                       */
#define STMT_HAS_NO_EFFECT  222 /* Statement has no effect                    */
#define MUST_BE_REENTRANT   223 /* Indirectly called function must be of
                                 * reentrant type                             */
#define CONFLICT_STR_PLACEMT 224 /* declared with the interrupt keyword       */
#define ISR_MUST_BE_VOID    225 /* Interrupt routine cannot have arguments or 
								   return a value */
#define CANT_CALL_ISR       226 /* Cannot call an interrupt handler           */
#define BAD_SFR_ACCESS      227 /* Objects with the SFR type qualifiers cannot be 
								   accessed through pointers, arrays, or as struct 
								   members */
#define TYPE_QUAL_DISABLED  228 /* Variable declared with a type qualifier that
                                   is not currently enabled */

/*
 * Note: Warnings generated by the compiler optimizer, backend, or assembler,
 * that is, beyond this point, cannot by specified by the suppress option.
 */

/*
 * Warnings generated by the compiler optimizer
 */
#define CANT_GEN_PRINTF_FMT 301 /* Can't preprocess format to (s)printf       */
#define TOO_MANY_PRINTF_ARG 304 /* Too many parameters for (s)printf format   */
#define MISSING_PRINTF_DECL 305 /* "Missing declaration of (s)printf helper
                                 * function, variable, or field               */
#define CANT_GEN_VPRINTF    306 /* Can't preprocess calls to vprintf or
                                 * vsprintf                                   */
#define NOT_ALL_PATHS_RET   307 /* Not all paths through [function] return a
                                 * value                                      */
#define USED_BEFORE_DEF     308 /* Variable [name] may be used before is is 
                                   defined                                    */
#define NO_CONFIG_FILE      309 /* The compiler configuration file such as 
                                   bin\eZ8.ini could not be read              */
#define BAD_CONFIG_FILE     310 /* The compiler configuration file such as 
                                   bin\eZ8.ini contains illegal syntax or 
								   commands                                   */
#define DIV_BY_ZERO         311 /* Division by zero detected at compile time  */
#define INTERNAL_ERROR      312 /* Optimizer internal error */

/*
 * Warnings generated by the compiler backend
 */
#define OUT_OF_RANGE        404 /* Constant value out of range                */
#define NOT_EXPANDED        422 /* Equates/Macros not expanded, translation
                                 * may not be exact                           */
#define TOO_MANY_TEMPS      431 /* Too many temporaries; CSE optimization
                                 * disabled for this function                 */

